/* GENERATED by tools/fontgen/make_font.py - do not edit. */
#ifndef AC_FONT_H
#define AC_FONT_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    uint8_t  first, last;
    uint8_t  height;      /* rows in the bitmap */
    int8_t   baseline;    /* rows from the top to the baseline */
    const uint16_t *offset;   /* index into bits, per glyph */
    const uint8_t  *width;    /* ink width, per glyph */
    const uint8_t  *advance;  /* pen advance, per glyph */
    const int8_t   *top;      /* rows from the top of the box */
    const uint8_t  *bits;     /* column-major, MSB first */
} ac_font_t;

extern const ac_font_t ac_font_small;   /* 12 px, 1436 B */
extern const ac_font_t ac_font_medium;   /* 20 px, 3897 B */
extern const ac_font_t ac_font_large;   /* 46 px, 3857 B */

#ifdef __cplusplus
}
#endif
#endif
