"""Rasterise DejaVu Sans into packed bitmap font tables for the e-paper UI.

The display is 200 x 200 1-bit pixels, so we carry our own fonts rather than
pulling in a rendering library.  Three faces are generated:

  small   12 px regular   labels, units, status lines
  medium  20 px bold      secondary values
  large   46 px bold      the primary numeral (digits and a few symbols only)

Glyphs are stored column-major, one bit per pixel, MSB first, with a per-glyph
width - proportional, not a fixed grid, because a fixed grid at 46 px wastes a
third of the screen on the gaps inside "1".

DejaVu Sans is under the Bitstream Vera / DejaVu licence, which permits
embedding and redistribution.  See firmware/components/ac_core/LICENSE-DejaVu.
"""
from __future__ import annotations

import os
import sys

from PIL import Image, ImageDraw, ImageFont

FONT_DIR = ("/Applications/FreeCAD.app/Contents/Resources/lib/python3.11/"
            "site-packages/matplotlib/mpl-data/fonts/ttf")
REG = os.path.join(FONT_DIR, "DejaVuSans.ttf")
BOLD = os.path.join(FONT_DIR, "DejaVuSans-Bold.ttf")

# The panel needs three characters that are not ASCII: micro, degree and
# superscript three.  Rather than carry the whole Latin-1 table for them, they
# are folded into three unused control codes so the glyph table stays a flat
# array starting at 1 instead of jumping to 0xB0.
SPECIAL = {1: "µ", 2: "°", 3: "³"}
AC_MICRO = "\\x01"
FULL = "".join(chr(c) for c in range(32, 127)) + "".join(SPECIAL.values())
NUM = "0123456789.,-+ %" + "".join(SPECIAL.values())

FACES = [
    ("small",  REG,  12, FULL),
    ("medium", BOLD, 20, FULL),
    ("large",  BOLD, 46, NUM),
]


def render(font, ch):
    # mode="L" gives one byte per pixel.  Asking for mode="1" here returns a
    # packed buffer that Image.frombytes then re-expands eight pixels wide,
    # which silently smears every glyph horizontally - it looks like text at a
    # glance and is unreadable on the panel.
    mask = font.getmask(ch, mode="L")
    w, h = mask.size
    img = Image.new("L", (max(w, 1), max(h, 1)), 0)
    if w and h:
        img.paste(Image.frombytes("L", (w, h), bytes(mask)), (0, 0))
    bbox = font.getbbox(ch)
    adv = int(round(font.getlength(ch)))
    return img, bbox, adv


def main() -> int:
    out_h = ["/* GENERATED by tools/fontgen/make_font.py - do not edit. */",
             "#ifndef AC_FONT_H", "#define AC_FONT_H", "",
             "#include <stdint.h>", "", "#ifdef __cplusplus",
             'extern "C" {', "#endif", "",
             "typedef struct {", "    uint8_t  first, last;",
             "    uint8_t  height;      /* rows in the bitmap */",
             "    int8_t   baseline;    /* rows from the top to the baseline */",
             "    const uint16_t *offset;   /* index into bits, per glyph */",
             "    const uint8_t  *width;    /* ink width, per glyph */",
             "    const uint8_t  *advance;  /* pen advance, per glyph */",
             "    const int8_t   *top;      /* rows from the top of the box */",
             "    const uint8_t  *bits;     /* column-major, MSB first */",
             "} ac_font_t;", ""]
    out_c = ["/* GENERATED by tools/fontgen/make_font.py - do not edit. */",
             '#include "ac_core/ac_font.h"', ""]

    for name, path, size, chars in FACES:
        font = ImageFont.truetype(path, size)
        asc, desc = font.getmetrics()
        height = asc + desc
        first = 1
        last = 126
        n = last - first + 1
        bits, offs, widths, advs, tops = bytearray(), [], [], [], []
        for code in range(first, last + 1):
            ch = SPECIAL.get(code, chr(code))
            offs.append(len(bits))
            if ch not in chars:
                widths.append(0); advs.append(0); tops.append(0)
                continue
            img, bbox, adv = render(font, ch)
            if bbox is None:
                widths.append(0); advs.append(adv); tops.append(0)
                continue
            x0, y0, x1, y1 = bbox
            w = max(x1 - x0, 0)
            h = max(y1 - y0, 0)
            px = img.load()
            iw, ih = img.size
            nbytes = (height + 7) // 8
            for col in range(w):
                colbits = bytearray(nbytes)
                for row in range(h):
                    sx, sy = col, row
                    if 0 <= sx < iw and 0 <= sy < ih and px[sx, sy] >= 128:
                        yy = y0 + row
                        if 0 <= yy < height:
                            colbits[yy >> 3] |= 0x80 >> (yy & 7)
                bits += colbits
            widths.append(w)
            advs.append(min(adv, 255))
            tops.append(max(min(y0, 127), -128))
        offs.append(len(bits))

        def arr(t, nm, vals):
            body = ", ".join(str(v) for v in vals)
            return f"static const {t} {nm}[] = {{ {body} }};"

        out_c.append(f"/* ---- {name}: {size} px, {len(bits)} bytes ---- */")
        out_c.append(arr("uint16_t", f"{name}_off", offs))
        out_c.append(arr("uint8_t", f"{name}_w", widths))
        out_c.append(arr("uint8_t", f"{name}_adv", advs))
        out_c.append(arr("int8_t", f"{name}_top", tops))
        hexes = ", ".join(f"0x{b:02X}" for b in bits)
        out_c.append(f"static const uint8_t {name}_bits[] = {{ {hexes} }};")
        out_c.append(f"const ac_font_t ac_font_{name} = {{")
        out_c.append(f"    {first}, {last}, {height}, {asc},")
        out_c.append(f"    {name}_off, {name}_w, {name}_adv, {name}_top, {name}_bits")
        out_c.append("};")
        out_c.append("")
        out_h.append(f"extern const ac_font_t ac_font_{name};   "
                     f"/* {size} px, {len(bits)} B */")

    out_h += ["", "#ifdef __cplusplus", "}", "#endif", "#endif"]

    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    hp = os.path.join(root, "firmware/components/ac_core/include/ac_core/ac_font.h")
    cp = os.path.join(root, "firmware/components/ac_core/src/ac_font_data.c")
    open(hp, "w").write("\n".join(out_h) + "\n")
    open(cp, "w").write("\n".join(out_c) + "\n")
    print(f"wrote {hp} and {cp} ({os.path.getsize(cp)/1024:.1f} kB of source)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
